server:
  port: 9051
spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings:  #绑定一个通道
        output:
          destination: xyy-default #指定消息发送的目的地,在rabbit中,发送到一个xyy-default的交换机上
      binders: #配置绑定器
        defaultRabbit:
          type: rabbit #消息队列的类型