CREATE TABLE TB_USER (
    ID NUMBER(10) NOT NULL,
    USER_NAME VARCHAR2(255) ,
    PASSWORD VARCHAR2(255) ,
    NAME VARCHAR2(255) ,
    AGE NUMBER(10) ,
    EMAIL VARCHAR2(255)
);
--创建序列
CREATE SEQUENCE SQE_USER1 START WITH 1 INCREMENT BY 1