spring:
  application:
    name: eureka-server
---
server:
  port: 7000
spring:
  profiles: eurekaserver1 #--spring.profiles.active=eurekaserver1
#配置eureka-server
eureka:
  client:
    register-with-eureka: true #是否将自己注册到注册中心
    fetch-registry: true #是否在注册中心获取注册信息
    service-url: #配置暴露给Eureka Client的请求地址
      defaultZone: http://127.0.0.1:7000/eureka/

---
server:
  port: 7001
spring:
  profiles: eurekaserver2 #--spring.profiles.active=eurekaserver1
#配置eureka-server
eureka:
  client:
    register-with-eureka: true #是否将自己注册到注册中心
    fetch-registry: true #是否在注册中心获取注册信息
    service-url: #配置暴露给Eureka Client的请求地址
      defaultZone: http://127.0.0.1:7000/eureka/
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 #设置剔除的服务间隔,单位(ms),默认60000L